import { useEffect } from "react";
import Head from "next/head";
import NextNProgress from "nextjs-progressbar";
import axios from "axios";

import Home from "../app/components/screens/home/Home";

import { getAllCryptocurrencies } from "../app/components/shared/axios/options";
import { ICryptocurrency } from "../app/components/shared/interfaces/cryptocurrency.types";

import type { GetStaticProps } from "next";

const HomePage = ({
  cryptocurrencies,
}: {
  cryptocurrencies: ICryptocurrency[];
}) => {
  useEffect(() => {
    console.log(cryptocurrencies);
  }, []);

  return (
    <div>
      <Head>
        <title>BeInCrypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextNProgress color="#d3a633" />
      <Home />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await axios.request(getAllCryptocurrencies);

  if (!res.data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { cryptocurrencies: res.data.data.coins },
  };
};

export default HomePage;
