import { useEffect } from "react";
import Head from "next/head";
import NextNProgress from "nextjs-progressbar";
import axios from "axios";
import Image from "next/image";
import { observer } from "mobx-react-lite";

import Home from "../app/components/screens/home/Home";

import { getAllCryptocurrencies } from "../app/components/shared/axios/options";
import { ICryptocurrency } from "../app/components/shared/interfaces/cryptocurrency.types";
import crypto from "../app/store/store";

import type { GetStaticProps } from "next";

const HomePage = observer(
  ({ cryptocurrencies }: { cryptocurrencies: ICryptocurrency[] }) => {
    return (
      <div>
        <Head>
          <title>BeInCrypto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NextNProgress color="#d3a633" />
        <Home cryptocurrencies={cryptocurrencies} />
      </div>
    );
  }
);

export const getStaticProps: GetStaticProps = async () => {
  const res = await axios.request(getAllCryptocurrencies);

  if (!res.data) {
    return {
      notFound: true,
    };
  }

  return {
    props: { cryptocurrencies: res.data.data.coins },
  };
};

export default HomePage;
